language: csharp
solution: CullenGlobalXAssessment.sln
mono: none
dotnet: 2.1.4

install:
- dotnet restore

script:
- dotnet build
- dotnet test CullenGlobalXAssessmentTests/CullenGlobalXAssessmentTests.csproj

notificatons:
    email: false
